project:
  type: website

website:
  title: "Karl Sparks"
  navbar:
    right:
      - blog.qmd
      - icon: github
        href: https://github.com/karl-sparks
      - icon: linkedin
        href: https://www.linkedin.com/in/karl-sparks/
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto



