---
title: "Proof of Concept"
author: "Karl Sparks"
date: "2023-10-05"
categories: 
  - resume-builder
  - poc
---

**Key Findings from Proof of Concept:**

1.  **LLMs for Resume Building:** LLMs, specifically GPT-4, proved effective in summarizing information for resume creation.

2.  **Context Sensitivity:** Output quality was sensitive to both context provided and the prompt template used.

3.  **Improvement Aspects:** To enhance output quality, three key aspects were identified:

    1.  **Validation Mechanism:** Essential for testing model changes and identifying better-performing versions, potentially using another LLM for validation.

    2.  **Feedback Mechanism:** Vital for refining the model and validation process based on user-detected errors and issues.

    3.  **Structured Output:** Implementing structured output to ensure consistency in the generated resumes.

# Proof of concept

First, I used ChatGPT-4 to make sure the use case is workable.

Although, GPT-4 is one of the most expensive LLMs available, I decided to go with GPT-4 because it is generally the best performing model for most use cases. If I can't get my use case working well with GPT-4 than I would unlikely be able to get it working with another model. The cost is also not that large at the proof of concept stage, although would be significant if scaled up.

For this proof of concept I will use Langchain to access GPT-4 and create the prompts. This API conveniently lets me set up the prompt in components based on a template. This lets met feed in additional information piece by piece, such as job description and resume experience. This functionality will be important when it comes to generallising this model to other jobs/resumes etc.

```{python}
import pandas as pd
import numpy as np
import os
import openai
from langchain.chat_models import ChatOpenAI
from langchain.prompts import PromptTemplate
from langchain.chains import LLMChain

llm = ChatOpenAI(model_name="gpt-4")
```

I create the prompt template below. When creating the template I experimented with a few different options to improve the outcome. This included using common recommendations such as including "lets think step by step", and specifying the output format.

```{python}
template = """You are helping create a resume for a job seeker (the candidate).

Use the following job description and information on the candidate background when answering the below question.

Make sure you do not make specific reference to skills or achievements that are not mentioned in the background.

The candidate is applying for a job as a {job_title} at a {company_name} with the job description as follows:
{job_description}

Candidate background: 
{context}

Question: Create a resume for the candedate. Make sure to include measureable metrics where possible.

Answer: Let's think step by step."""

prompt = PromptTemplate(template=template, input_variables=["context", "job_title", "company_name", "job_description"])

llm_chain = LLMChain(prompt=prompt, llm=llm)

job_title = "Machine Learning Engineer"

company_name = "Machinify"

job_description = """
Machinify is a revolutionary healthcare software company with a mission to ensure that patients get the right medical treatment, at the right time, at the right price. Our cloud-based Machinify AI platform leverages the latest advances in machine learning, large language models, data analytics, and cloud processing to solve previously intractable problems, transforming healthcare administration and payment operations.

We are seeking an ML Engineer to join our AI focused healthcare startup. Our team has deployed models that check for anomalies in medical claims, predict the trajectory of care of a particular patient and the next likely treatment and even “read and understand” medical record documents using state-of-the-art NLP and computer vision techniques to assist clinicians. There are many more such problems to be solved. So if you are looking for a place where you can apply your expertise in AI/ML to solve real problems and make a difference in an industry that impacts millions of lives while accelerating your career, you’ll love Machinify. We are seeking a Sr Machine Learning Scientist to join our team.

What you’ll do:
Advance Machinify’s capabilities to model and understand medical decisions which will power a range of products in the claims processing space. 
Make thoughtful decisions around which methods/algorithms are likely to work well in solving the business problem at hand
Consider the quality of the available input data and build robust systems that will work well in the presence of noise/errors
Measure the model output in practical real-world settings and iterate your approach 
Learn about the healthcare industry and become an expert over time

What You Bring:
You enjoy solving real-world business problems by developing, from scratch, ML models and deploying them in production - and have been doing that successfully for a while. 
You are comfortable measuring and optimizing the direct business impact of your work. 
You are interested in learning about the healthcare industry and helping us improve the care millions of people receive. 
You are scrappy, and love solving hard problems that matter. 
You are experienced with SQL, handling large-scale data, and are comfortable with at least one programming language (Python, R, etc.). 
You have experience building ML models using modern ML approaches like Neural Nets or Tree-ensembles from scratch for new applications - making decisions relating to which supervised labels to use, the metric to optimize for, and the features likely to be useful. 
You are a critical thinker who can be strategic without losing attention to detail. 
You are comfortable taking the initiative and owning projects from start to finish. 
You can build positive relationships based on trust and value delivered. 

The base salary for this position will vary based on an array of factors unique to each candidate such as qualifications, years and depth of experience, skill set, certifications, etc. The base salary range for this role is $180k-250k. We are hiring for different seniorities, and our Recruiting team will let you know if you qualify for a different role/range. Salary is one component of the total compensation package, which includes meaningful equity, excellent healthcare, flexible time off, and other benefits and perks.

Equal Employment Opportunity at Machinify

Machinify is committed to hiring talented and qualified individuals with diverse backgrounds for all of its positions. Machinify believes that the gathering and celebration of unique backgrounds, qualities, and cultures enriches the workplace.
"""

context = """
Work Experience:
  - Principal Analyst for the Austrlian Prudential Regulation Authority.
    - Extensively uses R and SQL to analyse data and produce reports.
    - Has a strong understanding of the Australian financial system.
    - Created R packages to automate the production of reports.
    - Created new automated reports to highlight the difference between old and new capital frameworks for everyone of the 114 reporting ADIs.
  - Senior Analyst for the Reserve Bank of Australia.
    - Used R to build and maintain models to monitor and forecast banks' funding costs.
    - Undertook economic and financial research to support the Bank's monetary policy and payment regulation functions.
    - Liaising with external and internal stakeholders for their expert opinions on different bank funding markets, drawing this all together to provide a comprehensive overview of funding conditions.
    - Monitoring of the quantity and price of bank funding sources such as deposits, bonds, securitisation and money markets using various data sources.
    - Analysing data collected through the Economic and Financial Statistics (EFS) collection. Including liaising with reporting institutions on reporting standards and data quality issues, and preparing data for publication.
    - Used R and SQL to build and maintain models to monitor and forecast banks' funding costs. to analyse data and forecasting the impact of changes in banks' funding conditions on average funding costs.
"""
```

The above prompt and context will create the below response from ChatGPT-4.

```{python}
answer = llm_chain.run({"context": context, "job_title": job_title, "company_name": company_name, "job_description": job_description})

print(answer)
```